uploads = []
outputs = []

[[generated]]
id = "0dUkSj35UnsyOR6NZU4w-"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4EpcEsNJOksnrbp2ll4j7"
uri = "file://artifacts/spacex-platform/src/assets/mars_texture.png"
type = "image"
title = "mars planet texture map"
